In [31]:
import tensorflow as tf
import os
import shutil
import glob
import random
import warnings
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Convolution2D,MaxPooling2D,Flatten #action detectionimport tensorflow
from tensorflow.keras import layers, models, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models  # Importing models module
import tensorflow as tf
import matplotlib.pyplot as plt
from IPython.display import HTML
import numpy as np
from keras.preprocessing import image


In [32]:

IMAGE_SIZE = 128
NUM_CLASSES = 4
DATA_DIR = r"C:\Users\narne\OneDrive\Desktop\Training"

# Function to load images and labels from directory
def load_data(data_dir):
    images = []
    labels = []
    classes = os.listdir(data_dir)
    for class_id, class_name in enumerate(classes):
        class_dir = os.path.join(data_dir, class_name)
        for image_name in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_name)
            img = image.load_img(image_path, target_size=(IMAGE_SIZE, IMAGE_SIZE))
            img_array = image.img_to_array(img)
            images.append(img_array)
            labels.append(class_id)
    return np.array(images), np.array(labels)


In [33]:

# Load training data
X_train, y_train = load_data(DATA_DIR)

# Normalize images
X_train = X_train / 255.0



In [34]:
# Convert labels to one-hot encoding
from keras.utils import to_categorical
y_train = to_categorical(y_train, NUM_CLASSES)

In [35]:
# Define test data directory
TEST_DATA_DIR = r"C:\Users\narne\OneDrive\Desktop\Testing"

# Function to load test images and labels from directory
def load_test_data(data_dir):
    images = []
    labels = []
    classes = os.listdir(data_dir)
    for class_id, class_name in enumerate(classes):
        class_dir = os.path.join(data_dir, class_name)
        for image_name in os.listdir(class_dir):
            image_path = os.path.join(class_dir, image_name)
            img = image.load_img(image_path, target_size=(IMAGE_SIZE, IMAGE_SIZE))
            img_array = image.img_to_array(img)
            images.append(img_array)
            labels.append(class_id)
    return np.array(images), np.array(labels)


In [36]:

# Load test data
X_test, y_test = load_test_data(TEST_DATA_DIR)

# Normalize test images
X_test = X_test / 255.0

# Convert test labels to one-hot encoding
y_test = to_categorical(y_test, NUM_CLASSES)




In [37]:
# Build CNN architecture model
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(IMAGE_SIZE, IMAGE_SIZE, 3)))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(NUM_CLASSES, activation='softmax'))


In [38]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
              

In [39]:
# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/10
133/133 [==============================] - 23s 158ms/step - loss: 0.6148 - accuracy: 0.7027 - val_loss: 0.6136 - val_accuracy: 0.7557
Epoch 2/10
133/133 [==============================] - 22s 162ms/step - loss: 0.3780 - accuracy: 0.8484 - val_loss: 0.4554 - val_accuracy: 0.8111
Epoch 3/10
133/133 [==============================] - 21s 161ms/step - loss: 0.2545 - accuracy: 0.9034 - val_loss: 0.3098 - val_accuracy: 0.8734
Epoch 4/10
133/133 [==============================] - 22s 164ms/step - loss: 0.1884 - accuracy: 0.9269 - val_loss: 0.2099 - val_accuracy: 0.9248
Epoch 5/10
133/133 [==============================] - 22s 166ms/step - loss: 0.1296 - accuracy: 0.9535 - val_loss: 0.1799 - val_accuracy: 0.9347
Epoch 6/10
133/133 [==============================] - 22s 164ms/step - loss: 0.0876 - accuracy: 0.9680 - val_loss: 0.1347 - val_accuracy: 0.9436
Epoch 7/10
133/133 [==============================] - 22s 165ms/step - loss: 0.0733 - accuracy: 0.9734 - val_loss: 0.1277 - val_ac

In [40]:
print(y_train)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]]


In [41]:
model.save("Brain_Tumor_Detection.h5")